apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: withinworkspace-policy-rule
spec:
  endpointSelector:
    matchLabels:
      "io.kubernetes.pod.namespace.labels.project-name": team-q
  ingress:
    - fromEndpoints:
        - matchLabels:
            "io.kubernetes.pod.namespace.labels.project-name": team-q
  egress:
    - toEndpoints:
        - matchLabels:
            "io.kubernetes.pod.namespace.labels.project-name": team-q